version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    restart: unless-stopped
    environment:
      - "ES_JAVA_OPTS=-Xms${MEM_SIZE_GB}g -Xmx${MEM_SIZE_GB}g"
      - "discovery.type=single-node"
    ports:
      - "${ELASTIC_PORT}:9200"
      - "9300:9300"
    networks:
      - esnet

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    restart: unless-stopped
    environment:
      - "server.host=0.0.0.0"
      - "elastic.url=http://elasticsearch:${ELASTIC_PORT}" 
    ports:
      - "5601:5601"
    depends_on: 
      - elasticsearch
    networks: 
      - esnet

networks: 
  esnet: